"""add request_body and response_body to chat_logs

Revision ID: 2dff421cd4e7
Revises: a2cf7a39fe86
Create Date: 2026-04-14 18:31:52.780008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dff421cd4e7'
down_revision: Union[str, None] = 'a2cf7a39fe86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_logs', sa.Column('request_body', sa.JSON(), nullable=True))
    op.add_column('chat_logs', sa.Column('response_body', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_logs', 'response_body')
    op.drop_column('chat_logs', 'request_body')
    # ### end Alembic commands ###
