"""initial schema

Revision ID: 96252e4767af
Revises: 
Create Date: 2026-04-14 18:22:12.891475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96252e4767af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_chat_logs_created_at', 'chat_logs', ['created_at'], unique=False)
    op.create_index('idx_chat_logs_model', 'chat_logs', ['model'], unique=False)
    op.create_index('idx_chat_logs_status_created', 'chat_logs', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_logs_status_created', table_name='chat_logs')
    op.drop_index('idx_chat_logs_model', table_name='chat_logs')
    op.drop_index('idx_chat_logs_created_at', table_name='chat_logs')
    # ### end Alembic commands ###
