"""add token quota to api_keys

Revision ID: a2cf7a39fe86
Revises: 96252e4767af
Create Date: 2026-04-14 18:27:57.561953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2cf7a39fe86'
down_revision: Union[str, None] = '96252e4767af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('token_quota', sa.BigInteger(), server_default='-1', nullable=False))
    op.add_column('api_keys', sa.Column('token_used', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'token_used')
    op.drop_column('api_keys', 'token_quota')
    # ### end Alembic commands ###
